### ISSUE TITLE
Specifying resources for the setup job machinekey container

### ISSUE THREAD

**Issue by meyfa** [zitadel/zitadel-charts#115]
### Problem

It's good practice to specify resource requests and limits for all workloads. As such, we are using an automated policy check (Datree) to ensure workloads have configured resources.

It is already possible to set `resources` for the setup job:

https://github.com/zitadel/zitadel-charts/blob/2e2f92072c0c63ecf4b950f8401f18258e6d2d15/charts/zitadel/values.yaml#L150

Unfortunately, this applies only to container 0 in the setup job template, and not to container 1 (the "machinekey" container). In other words, the following section has no way to define `resources`:

https://github.com/zitadel/zitadel-charts/blob/2e2f92072c0c63ecf4b950f8401f18258e6d2d15/charts/zitadel/templates/setupjob.yaml#L93-L107

This leads to Datree reporting the following 2 errors:

```
❌  Ensure each container has a configured memory limit  [1 occurrence]
    - metadata.name: release-name-zitadel-setup (kind: Job)
      > key: spec.template.spec.containers.1 (line: 565:11)
💡  Missing property object `limits.memory` - value should be within the accepted boundaries recommended by the organization
❌  Ensure each container has a configured memory request  [1 occurrence]
    - metadata.name: release-name-zitadel-setup (kind: Job)
      > key: spec.template.spec.containers.1 (line: 565:11)
💡  Missing property object `requests.memory` - value should be within the accepted boundaries recommended by the organization
```

### Proposed Solution

I think it would be acceptable to re-use the `setupJob.resources` for the machinekey container. Even better would be the ability to specify its resources separately (e.g., `setupJob.machinekeyWriter.resources`), with a fallback to `setupJob.resources`.

**Comment by eliobischof** [comment]
The proposed solution makes sense to me :+1:
