### ISSUE TITLE
Make test-connection pod optional

### ISSUE THREAD

**Issue by hobyte** [zitadel/zitadel-charts#124]
As a admin insting zitadel in my own infrastucture, I want to disable the test-connection pod as it always fails.

In my environment, installing zitadel takes some minutes, so the test-connection pod always fails. Because the deployment has both readinessProbe and startupProbe, this pod is redundant for me.

**Comment by eliobischof** [comment]
Do you run the tests with `helm test zitadel`?

**Comment by hobyte** [comment]
No, but I use 'helm template' in my pipeline, which includes the test-pod
