### ISSUE TITLE
feat: Add annotations to deployment / configMap resources

### ISSUE THREAD

**Issue by arnouthoebreckx** [zitadel/zitadel-charts#159]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

I would like to add ArgoCD sync-waves on top of the helm-hooks to further customize deployment order. Furthermore other services such as stakater reloader allows us to automatically restart our instance if any changes in secrets occur, this is also triggered by an annotation that is added to the deployment.

In general this change brings the resources inline with the other resources and allows for more customizability.

### Describe your ideal solution

Add the annotations tot he resources

**Comment by hifabienne** [comment]
@eliobischof @stebenz Whats you opinion about this?

**Comment by eliobischof** [comment]
> @eliobischof @stebenz Whats you opinion about this?

This is a great improvement, thanks a lot @arnouthoebreckx.
The PR is on automerge.
