### ISSUE TITLE
Add `--init-projections=true` to setup job

### ISSUE THREAD

**Issue by meyfa** [zitadel/zitadel-charts#168]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

In reference to https://github.com/zitadel/zitadel/issues/7302 - should the setup job be adapted to include `--init-projections=true`? Without it, manual intervention by a Kubernetes admin is necessary. We have to manually create a job description matching the setup job but with the flag added to the setup command, log into the cluster, and deploy it. This is not great when the deployment is managed via GitOps.

### Describe your ideal solution

As a DevOps engineer that deploys their infrastructure via Helm and GitOps, I want the chart to provide a proper upgrade path for newer Zitadel versions so that I don't have to break protocol and perform intensive (and error-prone) manual work for each update that changes the projections.

### Version

7.6.1

### App version

2.44.1

**Comment by fforootd** [comment]
I think this would be a good idea 😁 

@livio-a whats your take?

**Comment by eliobischof** [comment]
> I think this would be a good idea 😁 
> 
> @livio-a @stebenz @eliobischof whats your take?

Yes, we should add something like `additionalArguments` to the values for the setup job and default to --init-projections=true
