### ISSUE TITLE
Maybe add Prometheus Service and/or Pod Monitor

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel-charts#22]
To be discussed

**Comment by fforootd** [comment]
I think it could be helpful for k8s customers to have this available.

Although it only addresses the k8s and not the other platforms we support 😁

**Comment by eliobischof** [comment]
IMO we should make the Grafana config [available via a ConfigMap](https://github.com/grafana/helm-charts/tree/main/charts/grafana#sidecar-for-dashboards) for Grafana installations that have the sidecar. I think @thesephirot has another opinion?

Maybe we find a way to maintain the plain dashboard and prometheus configs in ZITADEL (for any platform) and use them it in the charts repo.
