### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by sprudel** [zitadel/zitadel-charts#254]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

What license does this the code in this repo have? Also Apache 2.0. ?

**Comment by eliobischof** [comment]
Yes, it's Apache 2.0
I liked the PR #256
