### ISSUE TITLE
Update chart version automatically

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel-charts#29]
Use commit messages to determine the next version

**Comment by eliobischof** [comment]
I think we can allow the linked PR to close this issue

**Comment by hifabienne** [comment]
@eliobischof please describe the user story

**Comment by eliobischof** [comment]
I think the benefits for removing a manual step don't add up to the added complexity and involvement of an additional tool in the pipeline. I'm cosing the issue for now.
