### ISSUE TITLE
v4 incompatible with rke2

### ISSUE THREAD

**Issue by AltF02** [zitadel/zitadel-charts#52]
## The issue

At https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/templates/setupjob.yaml#L90 it tries to pull `alpine/k8s` with the `kubernetesVersion`. 

Unfortunately on rke2 (and possibly k3s etc. too?) it tries to fetch `alpine/k8s:1.24.8+rke2r1` instead of `alpine/k8s:1.24.8`.

## Temp workaround
1. Clone https://github.com/zitadel/zitadel-charts
2. Edit `charts/zitadel/templates/setupjob.yaml`
3. Replace ` alpine/k8s:{{ include "zitadel.kubernetesVersion" . }}` with `alpine/k8s:1.24.8` where `1.24.8` is your k8s version
4. `helm install -f values.yaml my-zitadel ./zitadel-charts/charts/zitadel`

**Comment by eliobischof** [comment]
Thanks for reporting this.
AFAIU, you are helped when you can pin the image tag to a specific version like implemented in #55, right?
