### ISSUE TITLE
Installation as describe on the website fails with a nil pointer

### ISSUE THREAD

**Issue by stranljip** [zitadel/zitadel-charts#53]
When I try to install the chart as described on https://zitadel.com/docs/guides/deploy/kubernetes I get a nil pointer error:
```
helm install my-zitadel zitadel/zitadel \
  --set zitadel.masterkey="my-sophisticated-password" \
  --set zitadel.configmapConfig.ExternalSecure=false \
  --set zitadel.configmapConfig.TLS.Enabled=false \
  --set zitadel.secretConfig.Database.cockroach.User.Password="my-other-sophisticated-password" \
  --set replicaCount=1 \
  --set cockroachdb.single-node=true \
  --set cockroachdb.statefulset.replicas=1
Error: INSTALLATION FAILED: template: zitadel/templates/setupjob.yaml:82:74: executing "zitadel/templates/setupjob.yaml" at <.Values.zitadel.configmapConfig.FirstInstance.Org>: nil pointer evaluating interface {}.Org
```

I have not dug into the logic here but it seems to me that you have to apply a check on those values or use a nested if construction.

**Comment by AltF02** [comment]
I managed to work around this by adding under `zitadel`:

```
    FirstInstance:
      MachineKeyPath: /machinekey/zitadel-admin-sa.json 
      Org:
        Machine:
          Machine:
            Username: zitadel-admin-sa
            Name: Admin
          MachineKey:
            Type: 1
```

**Comment by eliobischof** [comment]
Thank you for reporting this.

The behavior in go templates was changed for go 1.18 which was just recently bumped in Helm, I guess. https://github.com/helm/helm/issues/11070.
With the newest helm version, helm uses a short circuit evaluation for and and or functions, so if you upgrade helm, you should get rid of the nil pointer.

Nevertheless, I'm going to change the templates so they are compatible with older versions as well.

**Comment by eliobischof** [comment]
@stranljip @AltF02, which helm versions do you use?

**Comment by stranljip** [comment]
I have to stall - I am currently on my private machine. I use the Helm version provided by Ranger Desktop, it is possible that this is not the latest version - I have to check that.

**Comment by hifabienne** [comment]
@stranljip Do you have any updates on this?

**Comment by stranljip** [comment]
I just tried the installation again and have a different error now (which I have to debug, I am probably missing something important in the setup). The initially described error is gone, from my side we can close this issue.
My Helm version atm is v3.10.2 (where the error does no longer occur ...). Thanks for your support!

**Comment by hifabienne** [comment]
> I just tried the installation again and have a different error now (which I have to debug, I am probably missing something important in the setup). The initially described error is gone, from my side we can close this issue. My Helm version atm is v3.10.2 (where the error does no longer occur ...). Thanks for your support!

Thanks for the reply. I will close this issue. Feel free to open up a new one if you have other problems. Or join our discord channel: https://zitadel.com/chat
