### ISSUE TITLE
helm template fails with given values

### ISSUE THREAD

**Issue by hobyte** [zitadel/zitadel-charts#66]
When using the [given helm values](https://zitadel.com/docs/self-hosting/deploy/kubernetes#install-an-insecure-cockroachdb-and-zitadel-release-that-works-with-localhost), `helm template` gives an error with the newest version of the chart:
```
$ helm template my-zitadel zitadel/zitadel \
  --set zitadel.masterkey="MasterkeyNeedsToHave32Characters" \
  --set zitadel.configmapConfig.ExternalSecure=false \
  --set zitadel.configmapConfig.TLS.Enabled=false \
  --set zitadel.secretConfig.Database.cockroach.User.Password="a-zitadel-db-user-password" \
  --set replicaCount=1 \
  --set cockroachdb.single-node=true \
  --set cockroachdb.statefulset.replicas=1
Error: template: zitadel/templates/setupjob.yaml:82:74: executing "zitadel/templates/setupjob.yaml" at <.Values.zitadel.configmapConfig.FirstInstance.Org>: nil pointer evaluating interface {}.Org

Use --debug flag to render out invalid YAML
```
Interestingly, installing works.

**Comment by eliobischof** [comment]
I think the nil pointer is due to an outdated Helm version, you use? I just created an issue that adresses this: https://github.com/zitadel/zitadel-charts/issues/68

Please reopen if your issue persists.
