### ISSUE TITLE
Chart fails when not using FirstInstance in values

### ISSUE THREAD

**Issue by krise86** [zitadel/zitadel-charts#69]
When installing the chart without defining FirstInstance the template fails with

`Error: INSTALLATION FAILED: template: zitadel/templates/setupjob.yaml:82:74: executing "zitadel/templates/setupjob.yaml" at <.Values.zitadel.configmapConfig.FirstInstance.Org>: nil pointer evaluating interface {}.Org`

**Comment by eliobischof** [comment]
Can you please update your helm version and try again? Please reopen the issue if the nil pointer persists.

@hifabienne I think we should take #68 into the next sprint.

**Comment by krise86** [comment]
yeah that worked, went from helm 3.7 to 3.11. thank you
