### ISSUE TITLE
Zitadel not connecting to the Postgres DB.

### ISSUE THREAD

**Issue by siddharthgaur2590** [zitadel/zitadel-charts#71]
Hi Team, cc: @mheers , @fforootd, @ansarhun @mffap 

I'm self-hosting Zitadel on K8s cluster using yamls like deployment, pv, pvc, service, ingress etc but its giving error when I'm connecting it to the self-hosted postgres DB in same cluster. 

**Error: cannot start client for projection: ID=DATAB-0pIWD Message=Errors.Database.Connection.Failed Parent=(failed to connect to `host=localhost user=zitadel database=zitadel`: dial error (dial tcp [::1]:26257: connect: connection refused))**

It seems due to some issue in connecting it with postgres, it's trying to connect to the default CockroachDB which I don't want.

Please help to give the resolution asap.

So far I've tried below options:

- Using configmap and referring it to the deployment.yaml
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: zitadel-config
      namespace: default
    data:
      ZITADEL_DB_TYPE: "postgresql"
      ZITADEL_DB_HOST: "lkjfkjsfkljskldfjs"
      ZITADEL_DB_PORT: "9897"
      ZITADEL_DB_NAME: "ffwefewfwef"
      ZITADEL_DB_USERNAME: "dsfdsf"
      ZITADEL_DB_PASSWORD: "r32re3"
      ZITADEL_DB_SSL_MODE: "disable"

- using the env variable in deployment.yaml
  env:
        - name: ZITADEL_DB_CONNECTION_URI
          value: postgresql://<username>:<password>@hostname:<port>/<dbname>

Also, another thing:
  I've used args like below in deployment.yaml, so anything else required to make the Zitadel instance up and running:
  args:
          - start
          - "--masterkey"
          - "custommasterkey"

**Comment by mffap** [comment]
> Please help to give the resolution asap.

Someone will get to it as soon as possible. I recommend also asking in our [discord chat](https://zitadel.com/chat) where many self-hosters help each other. If you need timely response we also offer a support program for self-hosting, for a quote please get in [touch with us](https://zitadel.com/contact).

Since you tagged me personally, I don't know how to help you with the issue since this is not my domain. Apologies.

**Comment by eliobischof** [comment]
You can see the supported configuration options in the defaults.yaml:  https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml#L82-L106

So the environment variable *ZITADEL_DB_CONNECTION_URI* does not have an effect.
According to https://zitadel.com/docs/self-hosting/manage/configure#environment-variables, you should rather configure *ZITADEL_DATABASE_POSTGRES_HOST*, *ZITADEL_DATABASE_POSTGRES_PORT* etc.

Please reopen the issue if that doesn't work for you.

**Comment by siddharthgaur2590** [comment]
Hi,
now following error comes, what other configs are required?

Error: cannot start client for projection: ID=DATAB-0pIWD Message=Errors.Database.Connection.Failed Parent=(cannot parse `host=xxxxxx.xxxxxx.svc.cluster.local port=5432 user= application_name=zitadel sslmode= dbname= sslrootcert=`: failed to configure TLS (sslmode is invalid))
