### ISSUE TITLE
TLS error showing while connecting to the postgres

### ISSUE THREAD

**Issue by siddharthgaur2590** [zitadel/zitadel-charts#72]
Hi,
now following error comes, what other configs are required?

Error: cannot start client for projection: ID=DATAB-0pIWD Message=Errors.Database.Connection.Failed Parent=(cannot parse `host=xxxxxx.xxxxxx.svc.cluster.local port=5432 user= application_name=zitadel sslmode= dbname= sslrootcert=`: failed to configure TLS (sslmode is invalid))

_Originally posted by @siddharthgaur2590 in https://github.com/zitadel/zitadel-charts/issues/71#issuecomment-1451738521_

**Comment by eliobischof** [comment]
Closing this, as it is a support request rather than a bug or a feature request.

For getting support, please refer to this answer https://github.com/zitadel/zitadel-charts/issues/71#issuecomment-1451615342
