### ISSUE TITLE
Outdated instructions on charts.zitadel.com

### ISSUE THREAD

**Issue by wesjdj** [zitadel/zitadel-charts#77]
The instructions on charts.zitadel.com are seemingly outdated, as it states:

> By default, this chart installs a highly available ZITADEL instance. Also it installs a highly available and secure CockroachDB by default.

The Readme in this repo however states:

> In v4, the cockroachdb chart dependency is removed.

**Comment by eliobischof** [comment]
That's true, we should update that. Thanks for the hint.
