### ISSUE TITLE
Helm install error when following the documentation

### ISSUE THREAD

**Issue by tbcashy** [zitadel/zitadel-charts#79]
I want to install Zitadel in a fresh kubernets cluster and following the documentation:

https://zitadel.com/docs/self-hosting/deploy/kubernetes

Installing CRDB works, but the Zitadel helm commands throws an error:

``Error: INSTALLATION FAILED: template: zitadel/templates/setupjob.yaml:82:74: executing "zitadel/templates/setupjob.yaml" at <.Values.zitadel.configmapConfig.FirstInstance.Org>: nil pointer evaluating interface {}.Org``

CRDB:
`helm upgrade --install crdb cockroachdb/cockroachdb \
  --set fullnameOverride=crdb \
  --set single-node=true \
  --set statefulset.replicas=1 --set tls.enabled=true`

Zitadel:

`helm install my-zitadel zitadel/zitadel \
  --set zitadel.masterkey="MasterkeyNeedsToHave32Characters" \
  --set zitadel.configmapConfig.ExternalSecure=false \
  --set zitadel.configmapConfig.TLS.Enabled=false \
  --set zitadel.secretConfig.Database.cockroach.User.Password="a-zitadel-db-user-password" \
  --set replicaCount=1
WARNING: "kubernetes-charts.storage.googleapis.com" is deprecated for "stable" and will be deleted Nov. 13, 2020.
WARNING: You should switch to "https://charts.helm.sh/stable" via:
WARNING: helm repo add "stable" "https://charts.helm.sh/stable" --force-update
Error: INSTALLATION FAILED: template: zitadel/templates/setupjob.yaml:82:74: executing "zitadel/templates/setupjob.yaml" at <.Values.zitadel.configmapConfig.FirstInstance.Org>: nil pointer evaluating interface {}.Org`

I also tested the second option which worked without placing it in a dedicated namespace. However I want to be able to login via the UI, so not just with a service account.

Thanks in advance for any help :)

**Comment by fforootd** [comment]
Can you share your helm version?

**Comment by tbcashy** [comment]
@fforootd Just added the repo, so the latest. In my case helm wanted to install 4.2.0.

**Comment by fforootd** [comment]
> @fforootd Just added the repo, so the latest. In my case helm wanted to install 4.2.0.

I meant `helm version` 😁 I just yesterday used the helm-chart with `version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.19.5"}`

**Comment by fforootd** [comment]
> Oh, sorry :D `version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}`
> 
> I updated to 3.11....now it works :D Thanks for the hint.

Nice good to know that this was the problem 👍
