### ISSUE TITLE
Unable to use helm chart with postgresql database

### ISSUE THREAD

**Issue by Be-El** [zitadel/zitadel-charts#82]
Hi,

the helm chart is focusing on cockroachdb deployments, which may be fine for cloud based setup.

We want to use zitadel on-premise with a baremetal postgresql cluster. Unfortunately the chart requires a number of cockroachdb related secret, certificates etc.

Do you have instructions how to use the chart with postgresql? Is it sufficient to fake the content of the required secrets?

**Comment by eliobischof** [comment]
Do I understand you correctly that you would like to have the secret data keys configurable [for these secrets](https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/values.yaml#L56-L63)?

Other connection secrets like username, password, host etc are configurable in the ZITADEL yaml [as described here](https://zitadel.com/docs/self-hosting/manage/database). For secret ZITADEL config, [you can use the secretConfig property](https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/values.yaml#L43) in the Helm values.

**Comment by Be-El** [comment]
Hi,

the helm chart requires certain secrets to be present. These are generated by cockroachdb. In a postgresql setup there is no cockroackdb, thus no secrets. This prevents the pods from starting since the secret cannot be mapped.

If I use empty fake secrets, the init container fails since it tries to copy /<secret mount>/* to some destination. This fails if the secret is empty and no files are present.

**Comment by Be-El** [comment]
An addition:

I can use fake secret content since the it is not used in the actual database setup in case of postgresql. Deployment fails nonetheless since the zitadel init code requires administrative access to the postgresql database. Since we have a shared postgreql cluster, we cannot use administrative credentials in third party applications. I've already created an issue in the zitadel core project, since code change will be required to solve this problem.

**Comment by eliobischof** [comment]
@Be-El, @vavsab I created a user story in #91 that should address your issues. Please track and participate in #91.
