### ISSUE TITLE
Image selection for the machineKey container does not work correctly

### ISSUE THREAD

**Issue by lusu007** [zitadel/zitadel-charts#87]
Currently, the Helm chart utilizes `{{ .Values.setupJob.machinekeyWriterImage.tag | default ( trimPrefix "v" .Capabilities.KubeVersion.Version ) }}` to select the version of the `alpine/k8s` image when no tag is specified in the `values.yaml` file.

However, this approach may not work reliably since `alpine/k8s` does not release a Docker image for every patch version of Kubernetes. For instance, if you're using Kubernetes 1.27.0, no corresponding `alpine/k8s` image is available for that particular version.

I'm unsure how this problem could be solved. Setting a static version in the Chart would restrict the Kubernetes version with which the Chart could be used.

**Comment by eliobischof** [comment]
We could default `setupJob.machinekeyWriterImage.repository` to `bitnami/kubectl`.
It seems to support more version tags. However, `1.27.0` is also not available :joy: 
But it's also slimmer than `alpine/k8s`.

**Comment by eliobischof** [comment]
Probably the best is `rancher/kubectl`.
It's the slimmest with 49.2MB, seems to support a lot of versions, and the version is prefixed with "v"

**Comment by eliobischof** [comment]
I realized, with a scratch image and without a shell, refactoring the command will be difficult :smile: 

`command: [ "sh","-c","until [ ! -z $(kubectl -n {{ .Release.Namespace }} get po ${POD_NAME} -o jsonpath=\"{.status.containerStatuses[?(@.name=='{{ .Chart.Name }}-setup')].state.terminated}\") ]; do echo 'waiting for {{ .Chart.Name }}-setup container to terminate'; sleep 5; done && echo '{{ .Chart.Name }}-setup container terminated' && if [ -f {{ default "/key" .Values.zitadel.configmapConfig.FirstInstance.MachineKeyPath }} ]; then kubectl -n {{ .Release.Namespace }} create secret generic {{ .Values.zitadel.configmapConfig.FirstInstance.Org.Machine.Machine.Username }} --from-file={{ .Values.zitadel.configmapConfig.FirstInstance.Org.Machine.Machine.Username }}.json={{ default "/key" .Values.zitadel.configmapConfig.FirstInstance.MachineKeyPath }}; fi;" ]
`

**Comment by lusu007** [comment]
LGTM! 😊
