### ISSUE TITLE
charts.zitadel.com doesn't resolve

### ISSUE THREAD

**Issue by juliusrickert** [zitadel/zitadel-charts#9]
I tried to take a look at Zitadel, which looks promising, but the repo's hostname doesn't resolve.

**Comment by fforootd** [comment]
👋 I think @eliobischof is still working on deploying the charts to the GH-pages, right @eliobischof ?

But that should be done soon

**Comment by juliusrickert** [comment]
It's resolving now. And #10 looks good too :)
